// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonWiki.DataAccess;

namespace PokemonWiki.DataAccess.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20220519212549_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokemonAttack", b =>
                {
                    b.Property<int>("PokemonPokemonId")
                        .HasColumnType("int");

                    b.Property<int>("AttacksAttackId")
                        .HasColumnType("int");

                    b.HasKey("PokemonPokemonId", "AttacksAttackId");

                    b.HasIndex("AttacksAttackId");

                    b.ToTable("PokemonAttack");

                    b.HasData(
                        new
                        {
                            PokemonPokemonId = 1,
                            AttacksAttackId = 1
                        },
                        new
                        {
                            PokemonPokemonId = 1,
                            AttacksAttackId = 2
                        },
                        new
                        {
                            PokemonPokemonId = 1,
                            AttacksAttackId = 3
                        },
                        new
                        {
                            PokemonPokemonId = 1,
                            AttacksAttackId = 4
                        },
                        new
                        {
                            PokemonPokemonId = 1,
                            AttacksAttackId = 5
                        },
                        new
                        {
                            PokemonPokemonId = 2,
                            AttacksAttackId = 6
                        },
                        new
                        {
                            PokemonPokemonId = 2,
                            AttacksAttackId = 7
                        },
                        new
                        {
                            PokemonPokemonId = 2,
                            AttacksAttackId = 8
                        },
                        new
                        {
                            PokemonPokemonId = 2,
                            AttacksAttackId = 9
                        },
                        new
                        {
                            PokemonPokemonId = 2,
                            AttacksAttackId = 10
                        },
                        new
                        {
                            PokemonPokemonId = 3,
                            AttacksAttackId = 11
                        },
                        new
                        {
                            PokemonPokemonId = 3,
                            AttacksAttackId = 12
                        },
                        new
                        {
                            PokemonPokemonId = 3,
                            AttacksAttackId = 13
                        },
                        new
                        {
                            PokemonPokemonId = 3,
                            AttacksAttackId = 14
                        },
                        new
                        {
                            PokemonPokemonId = 3,
                            AttacksAttackId = 15
                        },
                        new
                        {
                            PokemonPokemonId = 4,
                            AttacksAttackId = 16
                        },
                        new
                        {
                            PokemonPokemonId = 4,
                            AttacksAttackId = 17
                        },
                        new
                        {
                            PokemonPokemonId = 4,
                            AttacksAttackId = 18
                        },
                        new
                        {
                            PokemonPokemonId = 4,
                            AttacksAttackId = 19
                        },
                        new
                        {
                            PokemonPokemonId = 4,
                            AttacksAttackId = 20
                        },
                        new
                        {
                            PokemonPokemonId = 5,
                            AttacksAttackId = 21
                        },
                        new
                        {
                            PokemonPokemonId = 5,
                            AttacksAttackId = 22
                        },
                        new
                        {
                            PokemonPokemonId = 5,
                            AttacksAttackId = 23
                        },
                        new
                        {
                            PokemonPokemonId = 5,
                            AttacksAttackId = 24
                        },
                        new
                        {
                            PokemonPokemonId = 5,
                            AttacksAttackId = 25
                        },
                        new
                        {
                            PokemonPokemonId = 6,
                            AttacksAttackId = 26
                        },
                        new
                        {
                            PokemonPokemonId = 6,
                            AttacksAttackId = 27
                        },
                        new
                        {
                            PokemonPokemonId = 6,
                            AttacksAttackId = 28
                        },
                        new
                        {
                            PokemonPokemonId = 6,
                            AttacksAttackId = 29
                        },
                        new
                        {
                            PokemonPokemonId = 6,
                            AttacksAttackId = 30
                        },
                        new
                        {
                            PokemonPokemonId = 7,
                            AttacksAttackId = 31
                        },
                        new
                        {
                            PokemonPokemonId = 7,
                            AttacksAttackId = 32
                        },
                        new
                        {
                            PokemonPokemonId = 7,
                            AttacksAttackId = 33
                        },
                        new
                        {
                            PokemonPokemonId = 7,
                            AttacksAttackId = 34
                        },
                        new
                        {
                            PokemonPokemonId = 7,
                            AttacksAttackId = 35
                        },
                        new
                        {
                            PokemonPokemonId = 8,
                            AttacksAttackId = 36
                        },
                        new
                        {
                            PokemonPokemonId = 8,
                            AttacksAttackId = 37
                        },
                        new
                        {
                            PokemonPokemonId = 8,
                            AttacksAttackId = 38
                        },
                        new
                        {
                            PokemonPokemonId = 8,
                            AttacksAttackId = 39
                        },
                        new
                        {
                            PokemonPokemonId = 8,
                            AttacksAttackId = 40
                        },
                        new
                        {
                            PokemonPokemonId = 9,
                            AttacksAttackId = 41
                        },
                        new
                        {
                            PokemonPokemonId = 9,
                            AttacksAttackId = 42
                        },
                        new
                        {
                            PokemonPokemonId = 9,
                            AttacksAttackId = 43
                        },
                        new
                        {
                            PokemonPokemonId = 9,
                            AttacksAttackId = 44
                        },
                        new
                        {
                            PokemonPokemonId = 9,
                            AttacksAttackId = 45
                        });
                });

            modelBuilder.Entity("PokemonWiki.DataAccess.Models.Attack", b =>
                {
                    b.Property<int>("AttackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttackId");

                    b.ToTable("Attacks");

                    b.HasData(
                        new
                        {
                            AttackId = 1,
                            Name = "Thunderbolt"
                        },
                        new
                        {
                            AttackId = 2,
                            Name = "Discharge"
                        },
                        new
                        {
                            AttackId = 3,
                            Name = "Grass Knot"
                        },
                        new
                        {
                            AttackId = 4,
                            Name = "Brick Brake"
                        },
                        new
                        {
                            AttackId = 5,
                            Name = "Focus Punch"
                        },
                        new
                        {
                            AttackId = 6,
                            Name = "Overheat"
                        },
                        new
                        {
                            AttackId = 7,
                            Name = "Fire Blast"
                        },
                        new
                        {
                            AttackId = 8,
                            Name = "Flamethrower"
                        },
                        new
                        {
                            AttackId = 9,
                            Name = "Dig"
                        },
                        new
                        {
                            AttackId = 10,
                            Name = "Aerial Ace"
                        },
                        new
                        {
                            AttackId = 11,
                            Name = "Explosion"
                        },
                        new
                        {
                            AttackId = 12,
                            Name = "Giga Impact"
                        },
                        new
                        {
                            AttackId = 13,
                            Name = "Earthquake"
                        },
                        new
                        {
                            AttackId = 14,
                            Name = "Sludge Bomb"
                        },
                        new
                        {
                            AttackId = 15,
                            Name = "Psychic"
                        },
                        new
                        {
                            AttackId = 16,
                            Name = "Stone Edge"
                        },
                        new
                        {
                            AttackId = 17,
                            Name = "Fire Blast"
                        },
                        new
                        {
                            AttackId = 18,
                            Name = "Dragon Pulse"
                        },
                        new
                        {
                            AttackId = 19,
                            Name = "Surf"
                        },
                        new
                        {
                            AttackId = 20,
                            Name = "Rock Climb"
                        },
                        new
                        {
                            AttackId = 21,
                            Name = "Retaliate"
                        },
                        new
                        {
                            AttackId = 22,
                            Name = "Shadow Claw"
                        },
                        new
                        {
                            AttackId = 23,
                            Name = "Low Sweep"
                        },
                        new
                        {
                            AttackId = 24,
                            Name = "Fire Fang"
                        },
                        new
                        {
                            AttackId = 25,
                            Name = "Bulldoze"
                        },
                        new
                        {
                            AttackId = 26,
                            Name = "Fly"
                        },
                        new
                        {
                            AttackId = 27,
                            Name = "U-turn"
                        },
                        new
                        {
                            AttackId = 28,
                            Name = "Brave Bird"
                        },
                        new
                        {
                            AttackId = 29,
                            Name = "Flame Charge"
                        },
                        new
                        {
                            AttackId = 30,
                            Name = "Acrobatics"
                        },
                        new
                        {
                            AttackId = 31,
                            Name = "Solar Blade"
                        },
                        new
                        {
                            AttackId = 32,
                            Name = "Petal Blizzard"
                        },
                        new
                        {
                            AttackId = 33,
                            Name = "X-Scissor"
                        },
                        new
                        {
                            AttackId = 34,
                            Name = "Leaf Blade"
                        },
                        new
                        {
                            AttackId = 35,
                            Name = "Slash"
                        },
                        new
                        {
                            AttackId = 36,
                            Name = "Hyper Beam"
                        },
                        new
                        {
                            AttackId = 37,
                            Name = "Psybeam"
                        },
                        new
                        {
                            AttackId = 38,
                            Name = "Solar Beam"
                        },
                        new
                        {
                            AttackId = 39,
                            Name = "Mega Kick"
                        },
                        new
                        {
                            AttackId = 40,
                            Name = "Stomping Tantrum"
                        },
                        new
                        {
                            AttackId = 41,
                            Name = "Superpower"
                        },
                        new
                        {
                            AttackId = 42,
                            Name = "Dynamic Punch"
                        },
                        new
                        {
                            AttackId = 43,
                            Name = "Flash Cannon"
                        },
                        new
                        {
                            AttackId = 44,
                            Name = "Double Iron Bash"
                        },
                        new
                        {
                            AttackId = 45,
                            Name = "Self-Destruct"
                        });
                });

            modelBuilder.Entity("PokemonWiki.DataAccess.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            Description = "Pikachu (Japanese: ピカチュウ Pikachu) is an Electric-type Pokémon introduced in Generation I. It evolves from Pichu when leveled up with high friendship and evolves into Raichu when exposed to a Thunder Stone. Pikachu is popularly known as the mascot of the Pokémon franchise and one of Nintendo's major mascots.",
                            Evolution = "Raichu",
                            Name = "Pikachu",
                            PokemonImage = "pikachu.png",
                            PokemonType = "Electric",
                            Region = 1
                        },
                        new
                        {
                            PokemonId = 2,
                            Description = "Cyndaquil (Japanese: ヒノアラシ Hinoarashi) is a Fire-type Pokémon introduced in Generation II. It evolves into Quilava starting at level 14 (Generations II to VII, Brilliant Diamond and Shining Pearl) or level 17 (Legends: Arceus), which evolves into Typhlosion starting at level 36. Along with Chikorita and Totodile, Cyndaquil is one of the three starter Pokémon of Johto available at the beginning of Pokémon Gold, Silver, Crystal, HeartGold, and SoulSilver. It also acts as one of the three starters for the Hisui region in Legends: Arceus alongside Rowlet and Oshawott.",
                            Evolution = "Quilava -> Typhlosion",
                            Name = "Cyndaquil",
                            PokemonImage = "cyndaquil.png",
                            PokemonType = "Fire",
                            Region = 2
                        },
                        new
                        {
                            PokemonId = 3,
                            Description = "Beldum (Japanese: ダンバル Dumbber) is a dual-type Steel/Psychic Pokémon introduced in Generation III. It evolves into Metang starting at level 20, which evolves into Metagross starting at level 45.",
                            Evolution = "Metang -> Metagross",
                            Name = "Beldum",
                            PokemonImage = "beldum.png",
                            PokemonType = "Steel/Psychic",
                            Region = 3
                        },
                        new
                        {
                            PokemonId = 4,
                            Description = "Gible (Japanese: フカマル Fukamaru) is a dual-type Dragon/Ground Pokémon introduced in Generation IV. It evolves into Gabite starting at level 24, which evolves into Garchomp starting at level 48.",
                            Evolution = "Gabite -> Garchomp",
                            Name = "Gible",
                            PokemonImage = "gible.png",
                            PokemonType = "Dragon/Ground",
                            Region = 4
                        },
                        new
                        {
                            PokemonId = 5,
                            Description = "Sandile (Japanese: メグロコ Meguroco) is a dual-type Ground/Dark Pokémon introduced in Generation V. It evolves into Krokorok starting at level 29, which evolves into Krookodile starting at level 40.",
                            Evolution = "Krokorok -> Krookodile",
                            Name = "Sandile",
                            PokemonImage = "sandile.png",
                            PokemonType = "Ground/Dark",
                            Region = 5
                        },
                        new
                        {
                            PokemonId = 6,
                            Description = "Fletchling (Japanese: ヤヤコマ Yayakoma) is a dual-type Normal/Flying Pokémon introduced in Generation VI. It evolves into Fletchinder starting at level 17, which evolves into Talonflame starting at level 35.",
                            Evolution = "Fletchinder -> Talonflame",
                            Name = "Fletchling",
                            PokemonImage = "fletchling.png",
                            PokemonType = "Normal/Flying",
                            Region = 6
                        },
                        new
                        {
                            PokemonId = 7,
                            Description = "Fomantis (Japanese: カリキリ Karikiri) is a Grass-type Pokémon introduced in Generation VII. It evolves into Lurantis when leveled up in the day starting at level 34.",
                            Evolution = "Lurantis",
                            Name = "Fomantis",
                            PokemonImage = "fomantis.png",
                            PokemonType = "Grass",
                            Region = 7
                        },
                        new
                        {
                            PokemonId = 8,
                            Description = "Mr. Rime (Japanese: バリコオル Barrikohru) is a dual-type Ice/Psychic Pokémon introduced in Generation VIII. It evolves from Galarian Mr.Mime starting at level 42.It is the final form of Mime Jr. in the Galar region.",
                            Evolution = "Mr.Mime <-",
                            Name = "Mr. Rime",
                            PokemonImage = "mrrime.png",
                            PokemonType = "Ice/Psychic",
                            Region = 8
                        },
                        new
                        {
                            PokemonId = 9,
                            Description = "Meltan (Japanese: メルタン Meltan) is a Steel-type Mythical Pokémon introduced in Generation VII in Pokémon: Let's Go, Pikachu! and Let's Go, Eevee!. In Pokémon GO, it evolves into Melmetal by using 400 Meltan Candy. It cannot be evolved in other games. Its appearance was first teased during the September Pokémon GO Community Day on September 22, 2018, and it was officially revealed on September 25, 2018.",
                            Evolution = "Melmetal",
                            Name = "Meltan",
                            PokemonImage = "meltan.png",
                            PokemonType = "Steel",
                            Region = 0
                        });
                });

            modelBuilder.Entity("PokemonAttack", b =>
                {
                    b.HasOne("PokemonWiki.DataAccess.Models.Attack", null)
                        .WithMany()
                        .HasForeignKey("AttacksAttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonWiki.DataAccess.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("PokemonPokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
